name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform plan -var="version=${GITHUB_REF##*/}"
          terraform apply -var="version=${GITHUB_REF##*/}" -auto-approve

      - name: Create release
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = process.env.GITHUB_REF.replace('refs/tags/', '');
            const releaseTitle = `Release ${tagName}`;
            const releaseBody = `Automated release for version ${tagName}`;
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: releaseTitle,
              body: releaseBody,
              draft: false,
              prerelease: false,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}